kind: Deployment
apiVersion: apps/v1
metadata:
   name: pranit
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pranit
   template:
      metadata:
        labels:
          app: pranit
      spec:
       containers:
        - name: pranit
          image: pranitp2222/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
