kind: Service                             
apiVersion: v1
metadata:
  name: pranit
  labels:
    app: pranit
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: pranit                    
  type: LoadBalancer   